version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=db_uploader
      - SQL_USER=admin
      - SQL_PASSWORD=azertyuiopwxcvbn
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=azertyuiopwxcvbn
      - POSTGRES_DB=db_uploader
volumes:
  postgres_data: